name: Publish

on:
  push:
    # Mudado para rodar em QUALQUER branch que você der push pelo celular
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  build:
    uses: MinecraftForge/SharedActions/.github/workflows/gradle.yml@main
    with:
      java: 8
      # Adicionado o 'genPatches' para alinhar os patches com a nova versão automaticamente
      gradle_tasks: 'ciWriteBuildNumber setup genPatches build'
      legacy_prefix: 14
      legacy_build_number: 2848
      artifact_name: 'PotatoForge'
    secrets:
      PROMOTE_ARTIFACT_WEBHOOK: ${{ secrets.PROMOTE_ARTIFACT_WEBHOOK }}
      PROMOTE_ARTIFACT_USERNAME: ${{ secrets.PROMOTE_ARTIFACT_USERNAME }}
      PROMOTE_ARTIFACT_PASSWORD: ${{ secrets.PROMOTE_ARTIFACT_PASSWORD }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
